packages:
  - apps/*
  - packages/*
allowBuilds:
  "@prisma/engines": true
  "@scarf/scarf": true
  argon2: true
  esbuild: true
  msgpackr-extract: true
  prisma: true
overrides:
  deepmerge-ts: 8.0.1
